dist: xenial
sudo: true
language: python
env:
  global:
    - COVERALLS_PARALLEL=true

install:
  - pip install tox
  - pip install coveralls

script:
  - tox -e $TOX_ENV -- --hypothesis-profile=ci --durations=20
  - if [[ $TOX_ENV == py* ]]; then coveralls; fi  # Upload coverage results from py* environments.

jobs:
  include:
    - stage: test
      python: "2.7"
      env: TOX_ENV="lint2"
    - python: "3.6"
      env: TOX_ENV="lint3"
    - python: "2.7"
      env: TOX_ENV="py27"
    - python: "3.5"
      env: TOX_ENV="py35"
    - python: "3.6"
      env: TOX_ENV="py36"
    - python: "3.7"
      env: TOX_ENV="py37"

    - stage: deploy
      install: skip
      script: skip
      deploy:
        provider: pypi
        user: mark_bell
        password:
          secure: KTPvGFbFz3NBhFIIeaiRjEe56BAovWFWXJCBquwwH9yQX0k6WoBXfO+/KcbBLXOCrIns/vMlneh+gwY8r1UgCaV8V8sQg8nUUybxnHCFaCxcRmgqN3rr0QmRQYwpngEAGlqfSVnZmdP5/JwT7FE+GruQ0j9ny+N/3LQIJhFKTWy5QzzVgMepr5M21e3V0zIQzFnEGXk84JXbTkxntWhFoaO8fU3T6B1FSS7oluNQa6rLxFlLscTmgbvMdVL2gPzNFoXvNwKRQHW2iKU6+DirPQPyhWakbdROK94UFWQSiH8a8M9A00nXWg3crwf3VSFAJ0BkIWLvvCD0sZYXp84JOw+r2+xS3gFE9/R60NyP4HwFBApdJ16ghK3zXkCVbF9yPdPRTNiyLZuMTzbba3S2WqEqKuRY1TOrW+5PKN0vd3NCWnyzEYyynVAVx0ovI7wTcnobqxV5cJBPu9U/g4N/Y+oEf81DcbW+BM5bU7wLS3xjE//VxbBpAfuHUAMMAglod8YFKsz6t6QbEU/YCrTKitk9x3yYd5Xp7lnjvRDd8L3RS2Pm6jpLPsXzg6Zcp4Z5XSwrrLyhSDQ6UGcP3cVYVanhPdznY9rdr3K7REOrn683bfGUOtMMuCPVOYwbdI5i/OMQECnu6nDaNKvM3UAlVJEShWzAmSIe/c0nxlV4lxw=
        on:
          tags: true

