dist: xenial
sudo: true
language: python
env:
  global:
    - COVERALLS_PARALLEL=true

install:
  - pip install tox
  - pip install coveralls

script:
  - tox -e $TOX_ENV -- --hypothesis-profile=ci --duration=20
  - if [[ $TOX_ENV == py* ]]; then coveralls; fi  # Upload coverage results from py* environments.

jobs:
  include:
    - stage: test
      python: "2.7"
      env: TOX_ENV="lint2"
    - python: "3.6"
      env: TOX_ENV="lint3"
    - python: "2.7"
      env: TOX_ENV="py27"
    - python: "3.5"
      env: TOX_ENV="py35"
    - python: "3.6"
      env: TOX_ENV="py36"
    - python: "3.7"
      env: TOX_ENV="py37"

    - stage: deploy
      install: skip
      script: skip
      deploy:
        provider: pypi
        user: mark_bell
        password:
          secure: vZasHYpFySfTe4bDAGHmXFVRTv8jHzUpbKOJZiPVF3FRCfGI71wX01W8+S2hpjIDT/m798HpADoONrHIwwlgfS51uorDLcKNWZiZIJ0Q7Ijxd1YZaMYSnwHwrxAcCjIOd97ZQB9IZsmE8ox6DaWjahNRy/6PyDRrfDKSSOm04HUEqW//5Lhr1/js3j8tLTOjXIpxt9XaAJbS2vE4AsG29K1fYT31z0gLbmHuEecFr/xCBt5/0kae14mwYoWEqaZnuOVkZrt7G5A0RiMhY5mjOmQFKvr1pwTMFJU4zbc+Q9Dzsjgrh7krEkg//LVjghoPKxz2ViG1C0v9xPASN7Ht/Y5TnEewFlwbW1g7j/vfc8CtxB0ApAdTbn6oWbysY8U37OFUtiM9xMhOIuimpJBnhvfhHhFX67fLX6OVhYBaPhHqvyz8OfSDOXZsaBOoPvHtHeRUqlOmZTY02a14yVp2t03olGNzJWPlpB1OBMk0sOX+lZoNn3gmseyXye/KQePDD1EnBhTP91zyf9+QJ78S1uXvsyBVwXEJN7PgX8nZ3Fm5LKsw35hnVGFMD8y2Um7xZb818luaEStJFxw2lGCxaxwHCkDiOFz50p3GaAwVtOSS/yp4DcALQEJvXMBfw/9tiM8ez8BKBO2R6N2TwyXHAvhU8ysQ4CEC8L1hsg0Mh2w=
        on:
          tags: true

